[package]
edition = "2021"
name = "snos"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.3"
bincode = { version = "2.0.0-rc.3", default-features = false, features = [
    "serde",
] }
bitvec = { version = "1.0.1", features = ["serde"] }
blockifier = { git = "https://github.com/starkware-libs/blockifier", tag = "v0.4.0-rc9.2" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", features = ["extensive_hints"] }
hex = "0.4.3"
indexmap = "1.9.2"
indoc = "2"
lazy_static = "1.4.0"
log = "0.4.19"
num-integer = "0.1.45"
num-traits = "0.2.16"
regex = "1.10.0"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.105", features = ["arbitrary_precision"] }
serde_with = "3.3.0"
serde_yaml = "0.9.25"
starknet-crypto = "0.6.0"
starknet_api = { version = "0.7.0-dev.0", features = ["testing"] }
thiserror = "1.0.48"
tokio = "1.32.0"
uuid = { version = "1.4.0", features = ["v4", "serde"] }
zip = { version = "0.6.6", features = ["deflate-zlib"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
rstest = "0.18.2"

[patch."https://github.com/starkware-libs/blockifier"]
blockifier = { git = "https://github.com/dojoengine/blockifier", rev = "03a7e125f793de430c6c19f4003101a6c28f96ac" }

[patch.crates-io]
cairo-felt = { git = "https://github.com/dojoengine/cairo-rs.git", rev = "1031381" }
cairo-vm = { git = "https://github.com/dojoengine/cairo-rs.git", rev = "1031381" }
